// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greet/greetpb/greet.proto

package greetpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{1}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

// The response message containing the greetings
type GreetReponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetReponse) Reset()         { *m = GreetReponse{} }
func (m *GreetReponse) String() string { return proto.CompactTextString(m) }
func (*GreetReponse) ProtoMessage()    {}
func (*GreetReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{2}
}

func (m *GreetReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetReponse.Unmarshal(m, b)
}
func (m *GreetReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetReponse.Marshal(b, m, deterministic)
}
func (m *GreetReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetReponse.Merge(m, src)
}
func (m *GreetReponse) XXX_Size() int {
	return xxx_messageInfo_GreetReponse.Size(m)
}
func (m *GreetReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetReponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetReponse proto.InternalMessageInfo

func (m *GreetReponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetManyTimesRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetManyTimesRequest) Reset()         { *m = GreetManyTimesRequest{} }
func (m *GreetManyTimesRequest) String() string { return proto.CompactTextString(m) }
func (*GreetManyTimesRequest) ProtoMessage()    {}
func (*GreetManyTimesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{3}
}

func (m *GreetManyTimesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyTimesRequest.Unmarshal(m, b)
}
func (m *GreetManyTimesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyTimesRequest.Marshal(b, m, deterministic)
}
func (m *GreetManyTimesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyTimesRequest.Merge(m, src)
}
func (m *GreetManyTimesRequest) XXX_Size() int {
	return xxx_messageInfo_GreetManyTimesRequest.Size(m)
}
func (m *GreetManyTimesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyTimesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyTimesRequest proto.InternalMessageInfo

func (m *GreetManyTimesRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

// The response message containing the greetings
type GreetManyTimesReponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetManyTimesReponse) Reset()         { *m = GreetManyTimesReponse{} }
func (m *GreetManyTimesReponse) String() string { return proto.CompactTextString(m) }
func (*GreetManyTimesReponse) ProtoMessage()    {}
func (*GreetManyTimesReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{4}
}

func (m *GreetManyTimesReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyTimesReponse.Unmarshal(m, b)
}
func (m *GreetManyTimesReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyTimesReponse.Marshal(b, m, deterministic)
}
func (m *GreetManyTimesReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyTimesReponse.Merge(m, src)
}
func (m *GreetManyTimesReponse) XXX_Size() int {
	return xxx_messageInfo_GreetManyTimesReponse.Size(m)
}
func (m *GreetManyTimesReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyTimesReponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyTimesReponse proto.InternalMessageInfo

func (m *GreetManyTimesReponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type LongGreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LongGreetRequest) Reset()         { *m = LongGreetRequest{} }
func (m *LongGreetRequest) String() string { return proto.CompactTextString(m) }
func (*LongGreetRequest) ProtoMessage()    {}
func (*LongGreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{5}
}

func (m *LongGreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetRequest.Unmarshal(m, b)
}
func (m *LongGreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetRequest.Marshal(b, m, deterministic)
}
func (m *LongGreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetRequest.Merge(m, src)
}
func (m *LongGreetRequest) XXX_Size() int {
	return xxx_messageInfo_LongGreetRequest.Size(m)
}
func (m *LongGreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetRequest proto.InternalMessageInfo

func (m *LongGreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

// The response message containing the greetings
type LongGreetReponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongGreetReponse) Reset()         { *m = LongGreetReponse{} }
func (m *LongGreetReponse) String() string { return proto.CompactTextString(m) }
func (*LongGreetReponse) ProtoMessage()    {}
func (*LongGreetReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{6}
}

func (m *LongGreetReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongGreetReponse.Unmarshal(m, b)
}
func (m *LongGreetReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongGreetReponse.Marshal(b, m, deterministic)
}
func (m *LongGreetReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongGreetReponse.Merge(m, src)
}
func (m *LongGreetReponse) XXX_Size() int {
	return xxx_messageInfo_LongGreetReponse.Size(m)
}
func (m *LongGreetReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongGreetReponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongGreetReponse proto.InternalMessageInfo

func (m *LongGreetReponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetEveryOneRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetEveryOneRequest) Reset()         { *m = GreetEveryOneRequest{} }
func (m *GreetEveryOneRequest) String() string { return proto.CompactTextString(m) }
func (*GreetEveryOneRequest) ProtoMessage()    {}
func (*GreetEveryOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{7}
}

func (m *GreetEveryOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryOneRequest.Unmarshal(m, b)
}
func (m *GreetEveryOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryOneRequest.Marshal(b, m, deterministic)
}
func (m *GreetEveryOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryOneRequest.Merge(m, src)
}
func (m *GreetEveryOneRequest) XXX_Size() int {
	return xxx_messageInfo_GreetEveryOneRequest.Size(m)
}
func (m *GreetEveryOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryOneRequest proto.InternalMessageInfo

func (m *GreetEveryOneRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

// The response message containing the greetings
type GreetEveryOneResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetEveryOneResponse) Reset()         { *m = GreetEveryOneResponse{} }
func (m *GreetEveryOneResponse) String() string { return proto.CompactTextString(m) }
func (*GreetEveryOneResponse) ProtoMessage()    {}
func (*GreetEveryOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{8}
}

func (m *GreetEveryOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryOneResponse.Unmarshal(m, b)
}
func (m *GreetEveryOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryOneResponse.Marshal(b, m, deterministic)
}
func (m *GreetEveryOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryOneResponse.Merge(m, src)
}
func (m *GreetEveryOneResponse) XXX_Size() int {
	return xxx_messageInfo_GreetEveryOneResponse.Size(m)
}
func (m *GreetEveryOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryOneResponse proto.InternalMessageInfo

func (m *GreetEveryOneResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.Greeting")
	proto.RegisterType((*GreetRequest)(nil), "greet.GreetRequest")
	proto.RegisterType((*GreetReponse)(nil), "greet.GreetReponse")
	proto.RegisterType((*GreetManyTimesRequest)(nil), "greet.GreetManyTimesRequest")
	proto.RegisterType((*GreetManyTimesReponse)(nil), "greet.GreetManyTimesReponse")
	proto.RegisterType((*LongGreetRequest)(nil), "greet.LongGreetRequest")
	proto.RegisterType((*LongGreetReponse)(nil), "greet.LongGreetReponse")
	proto.RegisterType((*GreetEveryOneRequest)(nil), "greet.GreetEveryOneRequest")
	proto.RegisterType((*GreetEveryOneResponse)(nil), "greet.GreetEveryOneResponse")
}

func init() { proto.RegisterFile("greet/greetpb/greet.proto", fileDescriptor_fe6f881da19a2871) }

var fileDescriptor_fe6f881da19a2871 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4b, 0x4f, 0x83, 0x40,
	0x10, 0xc7, 0xa5, 0x49, 0x6b, 0x19, 0x9f, 0x19, 0xdf, 0x54, 0x13, 0xc3, 0xc1, 0x34, 0x9a, 0xb4,
	0x4d, 0x7b, 0xf4, 0x60, 0x7c, 0x5f, 0x7c, 0x34, 0xe8, 0xc9, 0x8b, 0xa1, 0x66, 0x24, 0x24, 0x65,
	0xc1, 0x5d, 0xda, 0xa4, 0x5f, 0xc9, 0x4f, 0x69, 0x98, 0x6e, 0x11, 0x50, 0x39, 0xd4, 0x0b, 0x30,
	0x0f, 0x7e, 0xff, 0xd9, 0xff, 0x64, 0x61, 0xcf, 0x93, 0x44, 0x71, 0x9b, 0x9f, 0xd1, 0x60, 0xfa,
	0x6e, 0x45, 0x32, 0x8c, 0x43, 0xac, 0x72, 0x60, 0xdf, 0x40, 0xfd, 0x36, 0xf9, 0xf0, 0x85, 0x87,
	0x07, 0x00, 0xef, 0xbe, 0x54, 0xf1, 0xab, 0x70, 0x03, 0xda, 0x35, 0x0e, 0x8d, 0xa6, 0xe9, 0x98,
	0x9c, 0x79, 0x70, 0x03, 0xc2, 0x06, 0x98, 0x43, 0x77, 0x56, 0xad, 0x70, 0xb5, 0x9e, 0x24, 0x92,
	0xa2, 0x7d, 0x0a, 0xcb, 0xcc, 0x71, 0xe8, 0x63, 0x44, 0x2a, 0xc6, 0x13, 0xa8, 0x7b, 0x9a, 0xcb,
	0xa4, 0xa5, 0xee, 0x5a, 0x6b, 0x2a, 0x3f, 0x93, 0x73, 0xd2, 0x06, 0xfb, 0x28, 0xfd, 0x39, 0x0a,
	0x85, 0x22, 0xdc, 0x86, 0x9a, 0x24, 0x35, 0x1a, 0xc6, 0x7a, 0x08, 0x1d, 0xd9, 0x57, 0xb0, 0xc5,
	0x7d, 0xf7, 0xae, 0x98, 0x3c, 0xfb, 0x01, 0xa9, 0xb9, 0xd4, 0xda, 0x3f, 0x29, 0xe5, 0xb2, 0x67,
	0xb0, 0x7e, 0x17, 0x0a, 0x6f, 0xfe, 0xf3, 0x1d, 0xe7, 0x00, 0xe5, 0x62, 0x97, 0xb0, 0xc9, 0x7d,
	0xd7, 0x63, 0x92, 0x93, 0x47, 0x41, 0xff, 0x3a, 0xe2, 0x37, 0x44, 0x95, 0xaa, 0x76, 0x3f, 0x2b,
	0x7a, 0x05, 0x4f, 0x24, 0xc7, 0xfe, 0x1b, 0x61, 0x0f, 0xaa, 0x1c, 0xe3, 0x46, 0x56, 0x45, 0x0f,
	0x63, 0x15, 0x92, 0xcc, 0xb6, 0x17, 0xb0, 0x0f, 0xab, 0x79, 0x67, 0x71, 0x3f, 0xdb, 0x58, 0x5c,
	0x9b, 0xf5, 0x57, 0x55, 0xf3, 0x3a, 0x06, 0x9e, 0x83, 0x99, 0x3a, 0x87, 0x3b, 0xba, 0xbd, 0xb8,
	0x0c, 0xeb, 0x97, 0x82, 0x46, 0x34, 0x0d, 0xec, 0xc3, 0x4a, 0xce, 0x0b, 0x6c, 0x64, 0x55, 0x0b,
	0x36, 0xe7, 0x47, 0x2a, 0xda, 0x97, 0xf0, 0x3a, 0xc6, 0x85, 0xf9, 0xb2, 0xa8, 0x6f, 0xd4, 0xa0,
	0xc6, 0x97, 0xa9, 0xf7, 0x15, 0x00, 0x00, 0xff, 0xff, 0x01, 0x11, 0xa8, 0x0d, 0x69, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetServiceClient interface {
	// Sends a greeting
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetReponse, error)
	GreetManyTimes(ctx context.Context, in *GreetManyTimesRequest, opts ...grpc.CallOption) (GreetService_GreetManyTimesClient, error)
	LongGreet(ctx context.Context, opts ...grpc.CallOption) (GreetService_LongGreetClient, error)
	GreetEveryOne(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetEveryOneClient, error)
}

type greetServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetServiceClient(cc *grpc.ClientConn) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetReponse, error) {
	out := new(GreetReponse)
	err := c.cc.Invoke(ctx, "/greet.GreetService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) GreetManyTimes(ctx context.Context, in *GreetManyTimesRequest, opts ...grpc.CallOption) (GreetService_GreetManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[0], "/greet.GreetService/GreetManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetManyTimesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_GreetManyTimesClient interface {
	Recv() (*GreetManyTimesReponse, error)
	grpc.ClientStream
}

type greetServiceGreetManyTimesClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetManyTimesClient) Recv() (*GreetManyTimesReponse, error) {
	m := new(GreetManyTimesReponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) LongGreet(ctx context.Context, opts ...grpc.CallOption) (GreetService_LongGreetClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[1], "/greet.GreetService/LongGreet", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceLongGreetClient{stream}
	return x, nil
}

type GreetService_LongGreetClient interface {
	Send(*LongGreetRequest) error
	CloseAndRecv() (*LongGreetReponse, error)
	grpc.ClientStream
}

type greetServiceLongGreetClient struct {
	grpc.ClientStream
}

func (x *greetServiceLongGreetClient) Send(m *LongGreetRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceLongGreetClient) CloseAndRecv() (*LongGreetReponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LongGreetReponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) GreetEveryOne(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetEveryOneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[2], "/greet.GreetService/GreetEveryOne", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetEveryOneClient{stream}
	return x, nil
}

type GreetService_GreetEveryOneClient interface {
	Send(*GreetEveryOneRequest) error
	Recv() (*GreetEveryOneResponse, error)
	grpc.ClientStream
}

type greetServiceGreetEveryOneClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetEveryOneClient) Send(m *GreetEveryOneRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceGreetEveryOneClient) Recv() (*GreetEveryOneResponse, error) {
	m := new(GreetEveryOneResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServiceServer is the server API for GreetService service.
type GreetServiceServer interface {
	// Sends a greeting
	Greet(context.Context, *GreetRequest) (*GreetReponse, error)
	GreetManyTimes(*GreetManyTimesRequest, GreetService_GreetManyTimesServer) error
	LongGreet(GreetService_LongGreetServer) error
	GreetEveryOne(GreetService_GreetEveryOneServer) error
}

// UnimplementedGreetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetServiceServer struct {
}

func (*UnimplementedGreetServiceServer) Greet(ctx context.Context, req *GreetRequest) (*GreetReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (*UnimplementedGreetServiceServer) GreetManyTimes(req *GreetManyTimesRequest, srv GreetService_GreetManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetManyTimes not implemented")
}
func (*UnimplementedGreetServiceServer) LongGreet(srv GreetService_LongGreetServer) error {
	return status.Errorf(codes.Unimplemented, "method LongGreet not implemented")
}
func (*UnimplementedGreetServiceServer) GreetEveryOne(srv GreetService_GreetEveryOneServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetEveryOne not implemented")
}

func RegisterGreetServiceServer(s *grpc.Server, srv GreetServiceServer) {
	s.RegisterService(&_GreetService_serviceDesc, srv)
}

func _GreetService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.GreetService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_GreetManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetManyTimesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).GreetManyTimes(m, &greetServiceGreetManyTimesServer{stream})
}

type GreetService_GreetManyTimesServer interface {
	Send(*GreetManyTimesReponse) error
	grpc.ServerStream
}

type greetServiceGreetManyTimesServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetManyTimesServer) Send(m *GreetManyTimesReponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetService_LongGreet_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).LongGreet(&greetServiceLongGreetServer{stream})
}

type GreetService_LongGreetServer interface {
	SendAndClose(*LongGreetReponse) error
	Recv() (*LongGreetRequest, error)
	grpc.ServerStream
}

type greetServiceLongGreetServer struct {
	grpc.ServerStream
}

func (x *greetServiceLongGreetServer) SendAndClose(m *LongGreetReponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceLongGreetServer) Recv() (*LongGreetRequest, error) {
	m := new(LongGreetRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_GreetEveryOne_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).GreetEveryOne(&greetServiceGreetEveryOneServer{stream})
}

type GreetService_GreetEveryOneServer interface {
	Send(*GreetEveryOneResponse) error
	Recv() (*GreetEveryOneRequest, error)
	grpc.ServerStream
}

type greetServiceGreetEveryOneServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetEveryOneServer) Send(m *GreetEveryOneResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceGreetEveryOneServer) Recv() (*GreetEveryOneRequest, error) {
	m := new(GreetEveryOneRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreetService_Greet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetManyTimes",
			Handler:       _GreetService_GreetManyTimes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LongGreet",
			Handler:       _GreetService_LongGreet_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GreetEveryOne",
			Handler:       _GreetService_GreetEveryOne_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "greet/greetpb/greet.proto",
}
