// Code generated by protoc-gen-go. DO NOT EDIT.
// source: max/maxpb/max.proto

package maxpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MaxRequest struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxRequest) Reset()         { *m = MaxRequest{} }
func (m *MaxRequest) String() string { return proto.CompactTextString(m) }
func (*MaxRequest) ProtoMessage()    {}
func (*MaxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5dafae75adf7d8b, []int{0}
}

func (m *MaxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxRequest.Unmarshal(m, b)
}
func (m *MaxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxRequest.Marshal(b, m, deterministic)
}
func (m *MaxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxRequest.Merge(m, src)
}
func (m *MaxRequest) XXX_Size() int {
	return xxx_messageInfo_MaxRequest.Size(m)
}
func (m *MaxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MaxRequest proto.InternalMessageInfo

func (m *MaxRequest) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type MaxResponse struct {
	MaxNum               int64    `protobuf:"varint,1,opt,name=max_num,json=maxNum,proto3" json:"max_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxResponse) Reset()         { *m = MaxResponse{} }
func (m *MaxResponse) String() string { return proto.CompactTextString(m) }
func (*MaxResponse) ProtoMessage()    {}
func (*MaxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5dafae75adf7d8b, []int{1}
}

func (m *MaxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxResponse.Unmarshal(m, b)
}
func (m *MaxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxResponse.Marshal(b, m, deterministic)
}
func (m *MaxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxResponse.Merge(m, src)
}
func (m *MaxResponse) XXX_Size() int {
	return xxx_messageInfo_MaxResponse.Size(m)
}
func (m *MaxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MaxResponse proto.InternalMessageInfo

func (m *MaxResponse) GetMaxNum() int64 {
	if m != nil {
		return m.MaxNum
	}
	return 0
}

func init() {
	proto.RegisterType((*MaxRequest)(nil), "max.maxRequest")
	proto.RegisterType((*MaxResponse)(nil), "max.maxResponse")
}

func init() { proto.RegisterFile("max/maxpb/max.proto", fileDescriptor_a5dafae75adf7d8b) }

var fileDescriptor_a5dafae75adf7d8b = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0x4d, 0xac, 0xd0,
	0xcf, 0x4d, 0xac, 0x28, 0x48, 0x02, 0x91, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xcc, 0xb9,
	0x89, 0x15, 0x4a, 0x72, 0x5c, 0x5c, 0xb9, 0x89, 0x15, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25,
	0x42, 0x02, 0x5c, 0xcc, 0x79, 0xa5, 0xb9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x20, 0xa6,
	0x92, 0x1a, 0x17, 0x37, 0x58, 0xbe, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x9c, 0x8b, 0x3d,
	0x37, 0xb1, 0x22, 0x1e, 0xa1, 0x88, 0x2d, 0x37, 0xb1, 0xc2, 0xaf, 0x34, 0xd7, 0xc8, 0x82, 0x0b,
	0x64, 0x9c, 0x90, 0x21, 0x17, 0x9b, 0x7b, 0x6a, 0x89, 0x6f, 0x62, 0x85, 0x10, 0xbf, 0x1e, 0xc8,
	0x26, 0x84, 0xd9, 0x52, 0x02, 0x08, 0x01, 0x88, 0x61, 0x4a, 0x0c, 0x1a, 0x8c, 0x06, 0x8c, 0x4e,
	0xec, 0x51, 0xac, 0x60, 0x97, 0x25, 0xb1, 0x81, 0x9d, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x65, 0x4f, 0x49, 0x49, 0xad, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MaxClient is the client API for Max service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MaxClient interface {
	GetMax(ctx context.Context, opts ...grpc.CallOption) (Max_GetMaxClient, error)
}

type maxClient struct {
	cc *grpc.ClientConn
}

func NewMaxClient(cc *grpc.ClientConn) MaxClient {
	return &maxClient{cc}
}

func (c *maxClient) GetMax(ctx context.Context, opts ...grpc.CallOption) (Max_GetMaxClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Max_serviceDesc.Streams[0], "/max.max/GetMax", opts...)
	if err != nil {
		return nil, err
	}
	x := &maxGetMaxClient{stream}
	return x, nil
}

type Max_GetMaxClient interface {
	Send(*MaxRequest) error
	Recv() (*MaxResponse, error)
	grpc.ClientStream
}

type maxGetMaxClient struct {
	grpc.ClientStream
}

func (x *maxGetMaxClient) Send(m *MaxRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *maxGetMaxClient) Recv() (*MaxResponse, error) {
	m := new(MaxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MaxServer is the server API for Max service.
type MaxServer interface {
	GetMax(Max_GetMaxServer) error
}

// UnimplementedMaxServer can be embedded to have forward compatible implementations.
type UnimplementedMaxServer struct {
}

func (*UnimplementedMaxServer) GetMax(srv Max_GetMaxServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMax not implemented")
}

func RegisterMaxServer(s *grpc.Server, srv MaxServer) {
	s.RegisterService(&_Max_serviceDesc, srv)
}

func _Max_GetMax_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MaxServer).GetMax(&maxGetMaxServer{stream})
}

type Max_GetMaxServer interface {
	Send(*MaxResponse) error
	Recv() (*MaxRequest, error)
	grpc.ServerStream
}

type maxGetMaxServer struct {
	grpc.ServerStream
}

func (x *maxGetMaxServer) Send(m *MaxResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *maxGetMaxServer) Recv() (*MaxRequest, error) {
	m := new(MaxRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Max_serviceDesc = grpc.ServiceDesc{
	ServiceName: "max.max",
	HandlerType: (*MaxServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMax",
			Handler:       _Max_GetMax_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "max/maxpb/max.proto",
}
